name: Deploy

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main


setup:
  runs-on: ubuntu-22.04
  outputs:
    deploy: ${{ steps.setup.outputs.deploy }}
  steps:
    - name: Setup
      id: setup
      run: |
        if [[ "${{ github.event_name }}" == "push" ]] && [[ ${{ github.ref }} == refs/heads/main ]]; then
          echo "deploy=true" >> "$GITHUB_OUTPUT"
        fi
        
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run tests
        run: |
          make test   
